<% if ENV['BAMBOO'] == 'true' %>

development:
  adapter: mysql2
  encoding: utf8
  database: blurtools_development
  host: nic-mysqldev01
  pool: 5
  username: blurtools_bamboo
  password: blurtools_bamboo

test:
  adapter: mysql2
  encoding: utf8
  database: blurtools_test
  host: nic-mysqldev01
  pool: 5
  username: blurtools_bamboo
  password: blurtools_bamboo

<% else %>

development:
  adapter: mysql2
  encoding: utf8
  database: blurtools_development
  host: localhost
  pool: 5
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  database: blurtools-test
  host: localhost
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: blurtools
  host: localhost
  pool: 5
  username: root
  password: 
<% end %>
